#!/usr/bin/env python3
"""
Apply VejaPRO email templates and auth config to Supabase via Management API.

Configures:
  - Site URL: https://vejapro.lt
  - Redirect URLs: https://vejapro.lt/**
  - Email templates: confirmation, recovery, magic_link (Lithuanian)

Usage:
    # Set your Supabase Management API token first:
    export SUPABASE_ACCESS_TOKEN="sbp_..."

    # Apply all config:
    python backend/scripts/apply_supabase_auth_config.py

    # Dry run (show what would be sent):
    python backend/scripts/apply_supabase_auth_config.py --dry-run

    # Verify current config:
    python backend/scripts/apply_supabase_auth_config.py --verify-only

Get your token at: https://supabase.com/dashboard/account/tokens
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path

PROJECT_REF = "oundiohbputdenshpeqk"
SUPABASE_API = "https://api.supabase.com"
SITE_URL = "https://vejapro.lt"
REDIRECT_URLS = "https://vejapro.lt/**"

# Template files generated by generate_supabase_email_templates.py
TEMPLATE_DIR = Path("/tmp")
TEMPLATES = {
    "confirmation": {
        "file": TEMPLATE_DIR / "supabase_confirmation.html",
        "subject": "VejaPRO - Patvirtinkite savo paskyra",
        "subject_field": "mailer_subjects_confirmation",
        "content_field": "mailer_templates_confirmation_content",
    },
    "recovery": {
        "file": TEMPLATE_DIR / "supabase_reset_password.html",
        "subject": "VejaPRO - Slaptazodzio atstatymas",
        "subject_field": "mailer_subjects_recovery",
        "content_field": "mailer_templates_recovery_content",
    },
    "magic_link": {
        "file": TEMPLATE_DIR / "supabase_magic_link.html",
        "subject": "VejaPRO - Prisijungimo nuoroda",
        "subject_field": "mailer_subjects_magic_link",
        "content_field": "mailer_templates_magic_link_content",
    },
}


def get_token() -> str:
    token = os.environ.get("SUPABASE_ACCESS_TOKEN", "")
    if not token:
        print("ERROR: SUPABASE_ACCESS_TOKEN env var not set.", file=sys.stderr)
        print("Get your token at: https://supabase.com/dashboard/account/tokens", file=sys.stderr)
        sys.exit(1)
    return token


def api_request(method: str, path: str, token: str, data: dict | None = None) -> dict:
    url = f"{SUPABASE_API}{path}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        error_body = e.read().decode() if e.fp else ""
        print(f"API error {e.code}: {error_body}", file=sys.stderr)
        sys.exit(1)


def get_auth_config(token: str) -> dict:
    return api_request("GET", f"/v1/projects/{PROJECT_REF}/config/auth", token)


def update_auth_config(token: str, payload: dict) -> dict:
    return api_request("PATCH", f"/v1/projects/{PROJECT_REF}/config/auth", token, payload)


def build_payload() -> dict:
    payload: dict = {
        "site_url": SITE_URL,
        "uri_allow_list": REDIRECT_URLS,
    }

    for name, tmpl in TEMPLATES.items():
        html_file = tmpl["file"]
        if not html_file.exists():
            print(f"WARNING: Template file not found: {html_file}", file=sys.stderr)
            print("  Run: python backend/scripts/generate_supabase_email_templates.py --type all", file=sys.stderr)
            print(f"  Skipping {name} template.", file=sys.stderr)
            continue

        html_content = html_file.read_text(encoding="utf-8")
        payload[tmpl["subject_field"]] = tmpl["subject"]
        payload[tmpl["content_field"]] = html_content

    return payload


def verify_config(config: dict) -> None:
    print("\n=== Dabartine Supabase Auth konfiguracija ===\n")

    site_url = config.get("site_url", "???")
    redirects = config.get("uri_allow_list", "???")
    ok = "\033[32mOK\033[0m"
    bad = "\033[31mNETEISINGA\033[0m"

    # Site URL
    status = ok if site_url == SITE_URL else bad
    print(f"  Site URL: {site_url}  [{status}]")

    # Redirect URLs
    status = ok if REDIRECT_URLS in str(redirects) else bad
    print(f"  Redirect URLs: {redirects}  [{status}]")

    # Email templates
    print("\n  Email sablonai:")
    for name, tmpl in TEMPLATES.items():
        subject = config.get(tmpl["subject_field"], "")
        content = config.get(tmpl["content_field"], "")
        has_subject = subject == tmpl["subject"]
        has_vejapro = "VejaPRO" in content and "vejapro.lt" in content

        subject_status = ok if has_subject else bad
        content_status = ok if has_vejapro else bad
        print(f"    {name}:")
        print(f"      Subject: {subject or '(tuscias)'}  [{subject_status}]")
        print(f"      Content: {'VejaPRO sablonas (' + str(len(content)) + ' chars)' if has_vejapro else '(default/tuscias, ' + str(len(content)) + ' chars)'}  [{content_status}]")

    print()


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply VejaPRO auth config to Supabase")
    parser.add_argument("--dry-run", action="store_true", help="Show payload without applying")
    parser.add_argument("--verify-only", action="store_true", help="Only check current config")
    args = parser.parse_args()

    token = get_token()

    if args.verify_only:
        config = get_auth_config(token)
        verify_config(config)
        return

    payload = build_payload()

    if args.dry_run:
        print("=== Dry run: payload that would be sent ===\n")
        # Show payload without full HTML (too long)
        display = {}
        for k, v in payload.items():
            if k.endswith("_content") and len(str(v)) > 100:
                display[k] = f"[HTML, {len(v)} chars, starts with: {v[:80]}...]"
            else:
                display[k] = v
        print(json.dumps(display, indent=2, ensure_ascii=False))
        return

    print(f"Taikome konfiguracija projektui {PROJECT_REF}...")
    print(f"  Site URL: {SITE_URL}")
    print(f"  Redirect URLs: {REDIRECT_URLS}")

    template_count = sum(1 for t in TEMPLATES.values() if t["file"].exists())
    print(f"  Email sablonai: {template_count}/{len(TEMPLATES)}")

    update_auth_config(token, payload)
    print("\nSekmingai atnaujinta!\n")

    # Verify
    print("Tikrinama...")
    config = get_auth_config(token)
    verify_config(config)


if __name__ == "__main__":
    main()
