import html as html_mod
import logging
from datetime import datetime, timezone

try:
    # WeasyPrint can fail to import on minimal Linux images when system deps
    # (cairo/pango/gdk-pixbuf) are missing. Keep module import safe so the API
    # can still start; PDF generation will error only when the endpoint is used.
    from weasyprint import HTML  # type: ignore
except Exception:  # pragma: no cover
    HTML = None  # type: ignore[assignment]

logger = logging.getLogger(__name__)


def generate_certificate_pdf(data: dict) -> bytes:
    """Generate a minimal certificate PDF using WeasyPrint."""
    if HTML is None:
        raise RuntimeError("PDF generavimas siuo metu nepasiekiamas (truksta WeasyPrint priklausomybiu)")

    project_id = html_mod.escape(str(data.get("project_id", "")))
    client_name = html_mod.escape(str(data.get("client_name", "Client")))
    certified_at = data.get("certified_at")
    area_m2 = data.get("area_m2")
    certified_text = html_mod.escape(
        certified_at.astimezone(timezone.utc).strftime("%Y-%m-%d")
        if isinstance(certified_at, datetime)
        else "N/A"
    )
    area_text = html_mod.escape(f"{area_m2} m2" if area_m2 is not None else "N/A")

    html_content = f"""
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body {{ font-family: Arial, sans-serif; margin: 48px; }}
          .title {{ font-size: 28px; font-weight: bold; margin-bottom: 16px; }}
          .subtitle {{ font-size: 16px; color: #444; margin-bottom: 24px; }}
          .row {{ margin-bottom: 8px; }}
          .label {{ font-weight: bold; }}
          .footer {{ margin-top: 32px; font-size: 12px; color: #666; }}
        </style>
      </head>
      <body>
        <div class="title">VejaPRO Certificate</div>
        <div class="subtitle">Project certification confirmation</div>
        <div class="row"><span class="label">Project ID:</span> {project_id}</div>
        <div class="row"><span class="label">Client:</span> {client_name}</div>
        <div class="row"><span class="label">Certified At:</span> {certified_text}</div>
        <div class="row"><span class="label">Area:</span> {area_text}</div>
        <div class="footer">Generated by VejaPRO</div>
      </body>
    </html>
    """

    try:
        return HTML(string=html_content).write_pdf()
    except Exception:
        logger.exception("Failed to generate certificate PDF for project %s", data.get("project_id"))
        raise
