from datetime import datetime, timezone

from weasyprint import HTML


def generate_certificate_pdf(data: dict) -> bytes:
    """Generate a minimal certificate PDF using WeasyPrint."""
    project_id = data.get("project_id", "")
    client_name = data.get("client_name", "Client")
    certified_at = data.get("certified_at")
    area_m2 = data.get("area_m2")
    certified_text = (
        certified_at.astimezone(timezone.utc).strftime("%Y-%m-%d")
        if isinstance(certified_at, datetime)
        else "N/A"
    )
    area_text = f"{area_m2} m2" if area_m2 is not None else "N/A"

    html = f"""
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body {{ font-family: Arial, sans-serif; margin: 48px; }}
          .title {{ font-size: 28px; font-weight: bold; margin-bottom: 16px; }}
          .subtitle {{ font-size: 16px; color: #444; margin-bottom: 24px; }}
          .row {{ margin-bottom: 8px; }}
          .label {{ font-weight: bold; }}
          .footer {{ margin-top: 32px; font-size: 12px; color: #666; }}
        </style>
      </head>
      <body>
        <div class="title">VejaPRO Certificate</div>
        <div class="subtitle">Project certification confirmation</div>
        <div class="row"><span class="label">Project ID:</span> {project_id}</div>
        <div class="row"><span class="label">Client:</span> {client_name}</div>
        <div class="row"><span class="label">Certified At:</span> {certified_text}</div>
        <div class="row"><span class="label">Area:</span> {area_text}</div>
        <div class="footer">Generated by VejaPRO</div>
      </body>
    </html>
    """

    return HTML(string=html).write_pdf()
